#pragma once

#include "Game.h"  // IWYU pragma: keep

typedef enum DispatchFnId /* : u32 */ {
  DISPATCH_NONE,

  CAT_ENTITY__TICK,
  CAT_SPAWN_BLOCK__TICK,
  DEBUG_TEXT__TICK,
  PLAYER_ENTITY__TICK,
  RUBBLE_SPRITE__TICK,
  SKY_BOX__TICK,
  SPAWN_BLOCK__TICK,

  // ABOUT_MENU__GUI,
  // ABOUT_MENU__RENDER,
  // ABOUT_MENU__TICK,
  // HELP_MENU__GUI,
  // HELP_MENU__RENDER,
  // HELP_MENU__TICK,
  // TITLE_MENU__GUI,
  // TITLE_MENU__RENDER,
  // TITLE_MENU__TICK,

  LEVEL__TICK,
  LEVEL__TICK__ARENA_RESET,
  LEVEL__TICK__QUADTREE_CREATE,
  LEVEL__RENDER,
  LEVEL__GUI,
  GAME__GUI,

  BREAK_BLOCK__ACTION,
  CAT_ENTITY__ACTION,
  CAT_ENTITY__COLLIDE,
  RED_WALL_BLOCK__ACTION,

  ATLAS__ONRENDER_LOAD,
  ATLAS__ONRENDER_ALLOC,
  ATLAS__ONRENDER_ENTITY,
  ATLAS__ONRENDER_MATERIAL,
  PBR__ONRENDER_LOAD,
  PBR__ONRENDER_ALLOC,
  PBR__ONRENDER_ENTITY,
  PBR__ONRENDER_MATERIAL,

  DISPATCH__COUNT,
} DispatchFnId;

void Dispatcher__call(u32 id, void* params);